codecov:
  require_ci_to_pass: false
comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
  hide_project_coverage: false
coverage:
  status:
    project:
      default:
        target: "100%"
        threshold: "0%"
    patch:
      default:
        target: "100%"
        threshold: "0%"
